// seeders/userSeeder.js

const mongoose = require("mongoose");

const dotenv = require("dotenv");

const bcrypt = require("bcryptjs");

const User = require("./models/User");

dotenv.config();



// ========================
// CONNECT DATABASE
// ========================

mongoose.connect(process.env.MONGODB_URI)
  .then(() => {
    console.log("MongoDB Connected");
  })
  .catch((err) => {
    console.log(err);
  });



// ========================
// USERS ARRAY
// ========================

// USERS ARRAY

// HIGH QUALITY 50 MATRIMONY USERS
const users = [

// ══════════════════════════════════════
// MALE USERS (50)
// ══════════════════════════════════════

{
  name: "Rahul Sharma",
  email: "rahul@gmail.com",
  phoneNumber: "9876543210",
  password: "123456",
  photos: ["https://images.unsplash.com/photo-1500648767791-00dcc994a43e"],
  gender: "Male",
  dateOfBirth: "1997-05-14",
  religion: "Hindu",
  motherTongue: "Hindi",
  maritalStatus: "Never Married",
  education: "B.Tech",
  occupation: "Software Engineer",
  city: "Hyderabad",
  state: "Telangana",
  bio: "Looking for a caring and understanding life partner.",
  hobbies: ["Travel", "Music", "Gym"],
  favoriteFoods: ["Biryani", "Pizza"],
  favoriteColor: "Blue",
  interests: ["Movies", "Technology", "Fitness"],
  personalityType: "Introvert",
  height: 175,
  annualIncome: 1200000,
  drinking: "Occasionally",
  smoking: "No",
  languagesKnown: ["Hindi", "English", "Telugu"],
  partnerPreferences: { ageMin: 22, ageMax: 28, religions: ["Hindu"], cities: ["Hyderabad", "Bangalore"], occupations: ["Engineer", "Doctor"] }
},

{
  name: "Arjun Kumar",
  email: "arjun@gmail.com",
  phoneNumber: "9876543212",
  password: "123456",
  photos: ["https://images.unsplash.com/photo-1519085360753-af0119f7cbe7"],
  gender: "Male",
  dateOfBirth: "1995-08-20",
  religion: "Hindu",
  motherTongue: "Tamil",
  maritalStatus: "Never Married",
  education: "M.Tech",
  occupation: "Backend Developer",
  city: "Chennai",
  state: "Tamil Nadu",
  bio: "Simple person with modern values.",
  hobbies: ["Cricket", "Photography"],
  favoriteFoods: ["Idli", "Chicken Curry"],
  favoriteColor: "Black",
  interests: ["Coding", "Gaming"],
  personalityType: "Ambivert",
  height: 178,
  annualIncome: 1500000,
  drinking: "Occasionally",
  smoking: "No",
  languagesKnown: ["Tamil", "English"],
  partnerPreferences: { ageMin: 22, ageMax: 30, religions: ["Hindu"], cities: ["Chennai", "Bangalore"], occupations: ["Teacher", "Engineer"] }
},

{
  name: "Karthik R",
  email: "karthik@gmail.com",
  phoneNumber: "9876543214",
  password: "123456",
  photos: ["https://images.unsplash.com/photo-1504257432389-52343af06ae3"],
  gender: "Male",
  dateOfBirth: "1996-11-09",
  religion: "Hindu",
  motherTongue: "Kannada",
  maritalStatus: "Never Married",
  education: "B.Tech",
  occupation: "UI UX Designer",
  city: "Mysore",
  state: "Karnataka",
  bio: "Creative and calm personality.",
  hobbies: ["Drawing", "Travel"],
  favoriteFoods: ["Burger", "South Indian"],
  favoriteColor: "Green",
  interests: ["Art", "Technology"],
  personalityType: "Introvert",
  height: 173,
  annualIncome: 1100000,
  drinking: "No",
  smoking: "No",
  languagesKnown: ["Kannada", "English"],
  partnerPreferences: { ageMin: 22, ageMax: 29, religions: ["Hindu"], cities: ["Mysore", "Bangalore"], occupations: ["Designer", "Engineer"] }
},

{
  name: "Vikram Singh",
  email: "vikram@gmail.com",
  phoneNumber: "9876543216",
  password: "123456",
  photos: ["https://images.unsplash.com/photo-1506794778202-cad84cf45f1d"],
  gender: "Male",
  dateOfBirth: "1994-12-05",
  religion: "Hindu",
  motherTongue: "Punjabi",
  maritalStatus: "Never Married",
  education: "MBA",
  occupation: "Business Analyst",
  city: "Delhi",
  state: "Delhi",
  bio: "Ambitious and family-loving person.",
  hobbies: ["Gym", "Cricket"],
  favoriteFoods: ["Butter Chicken", "Paneer"],
  favoriteColor: "Navy Blue",
  interests: ["Finance", "Sports"],
  personalityType: "Extrovert",
  height: 180,
  annualIncome: 1800000,
  drinking: "Occasionally",
  smoking: "No",
  languagesKnown: ["Hindi", "Punjabi", "English"],
  partnerPreferences: { ageMin: 23, ageMax: 30, religions: ["Hindu"], cities: ["Delhi", "Noida"], occupations: ["Manager", "Teacher"] }
},

{
  name: "Aditya Patel",
  email: "aditya@gmail.com",
  phoneNumber: "9876543220",
  password: "123456",
  photos: ["https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d"],
  gender: "Male",
  dateOfBirth: "1998-03-22",
  religion: "Hindu",
  motherTongue: "Gujarati",
  maritalStatus: "Never Married",
  education: "B.Tech",
  occupation: "Data Scientist",
  city: "Mumbai",
  state: "Maharashtra",
  bio: "Data enthusiast who loves solving real world problems.",
  hobbies: ["Chess", "Cycling", "Cooking"],
  favoriteFoods: ["Dhokla", "Sushi"],
  favoriteColor: "Orange",
  interests: ["AI", "Finance", "Travel"],
  personalityType: "Introvert",
  height: 172,
  annualIncome: 1600000,
  drinking: "No",
  smoking: "No",
  languagesKnown: ["Gujarati", "Hindi", "English"],
  partnerPreferences: { ageMin: 22, ageMax: 28, religions: ["Hindu"], cities: ["Mumbai", "Pune"], occupations: ["Engineer", "Doctor"] }
},

{
  name: "Rohan Mehta",
  email: "rohan@gmail.com",
  phoneNumber: "9876543221",
  password: "123456",
  photos: ["https://images.unsplash.com/photo-1528892952291-009c663ce843"],
  gender: "Male",
  dateOfBirth: "1993-07-11",
  religion: "Hindu",
  motherTongue: "Marathi",
  maritalStatus: "Never Married",
  education: "CA",
  occupation: "Chartered Accountant",
  city: "Pune",
  state: "Maharashtra",
  bio: "Finance professional with a love for trekking.",
  hobbies: ["Trekking", "Reading", "Badminton"],
  favoriteFoods: ["Misal Pav", "Pasta"],
  favoriteColor: "Brown",
  interests: ["Finance", "Nature", "Sports"],
  personalityType: "Ambivert",
  height: 176,
  annualIncome: 2000000,
  drinking: "Occasionally",
  smoking: "No",
  languagesKnown: ["Marathi", "Hindi", "English"],
  partnerPreferences: { ageMin: 24, ageMax: 30, religions: ["Hindu"], cities: ["Pune", "Mumbai"], occupations: ["Doctor", "Engineer"] }
},

{
  name: "Siddharth Joshi",
  email: "siddharth@gmail.com",
  phoneNumber: "9876543222",
  password: "123456",
  photos: ["https://images.unsplash.com/photo-1463453091185-61582044d556"],
  gender: "Male",
  dateOfBirth: "1996-01-30",
  religion: "Hindu",
  motherTongue: "Hindi",
  maritalStatus: "Never Married",
  education: "B.Tech",
  occupation: "DevOps Engineer",
  city: "Bangalore",
  state: "Karnataka",
  bio: "Tech guy who loves hiking on weekends.",
  hobbies: ["Hiking", "Gaming", "Music"],
  favoriteFoods: ["Pizza", "Biryani"],
  favoriteColor: "Grey",
  interests: ["Technology", "Travel", "Fitness"],
  personalityType: "Introvert",
  height: 177,
  annualIncome: 1400000,
  drinking: "No",
  smoking: "No",
  languagesKnown: ["Hindi", "English", "Kannada"],
  partnerPreferences: { ageMin: 22, ageMax: 29, religions: ["Hindu"], cities: ["Bangalore", "Hyderabad"], occupations: ["Engineer", "Manager"] }
},

{
  name: "Nikhil Rao",
  email: "nikhil@gmail.com",
  phoneNumber: "9876543223",
  password: "123456",
  photos: ["https://images.unsplash.com/photo-1542909168-82c3e7fdcd5b"],
  gender: "Male",
  dateOfBirth: "1995-04-18",
  religion: "Hindu",
  motherTongue: "Telugu",
  maritalStatus: "Never Married",
  education: "M.Tech",
  occupation: "AI Engineer",
  city: "Hyderabad",
  state: "Telangana",
  bio: "Building the future with AI.",
  hobbies: ["Coding", "Gym", "Travel"],
  favoriteFoods: ["Biryani", "Noodles"],
  favoriteColor: "Blue",
  interests: ["AI", "Technology", "Fitness"],
  personalityType: "Introvert",
  height: 174,
  annualIncome: 2200000,
  drinking: "No",
  smoking: "No",
  languagesKnown: ["Telugu", "English", "Hindi"],
  partnerPreferences: { ageMin: 23, ageMax: 29, religions: ["Hindu"], cities: ["Hyderabad", "Bangalore"], occupations: ["Engineer", "Doctor"] }
},

{
  name: "Amit Verma",
  email: "amit@gmail.com",
  phoneNumber: "9876543224",
  password: "123456",
  photos: ["https://images.unsplash.com/photo-1566492031773-4f4e44671857"],
  gender: "Male",
  dateOfBirth: "1994-09-25",
  religion: "Hindu",
  motherTongue: "Hindi",
  maritalStatus: "Never Married",
  education: "MBA",
  occupation: "Marketing Manager",
  city: "Delhi",
  state: "Delhi",
  bio: "Creative thinker with a passion for brands.",
  hobbies: ["Photography", "Travel", "Cricket"],
  favoriteFoods: ["Chole Bhature", "Momos"],
  favoriteColor: "Red",
  interests: ["Marketing", "Travel", "Sports"],
  personalityType: "Extrovert",
  height: 179,
  annualIncome: 1300000,
  drinking: "Occasionally",
  smoking: "No",
  languagesKnown: ["Hindi", "English"],
  partnerPreferences: { ageMin: 23, ageMax: 30, religions: ["Hindu"], cities: ["Delhi", "Mumbai"], occupations: ["Manager", "Doctor"] }
},

{
  name: "Pranav Kulkarni",
  email: "pranav@gmail.com",
  phoneNumber: "9876543225",
  password: "123456",
  photos: ["https://images.unsplash.com/photo-1599566150163-29194dcaad36"],
  gender: "Male",
  dateOfBirth: "1997-12-01",
  religion: "Hindu",
  motherTongue: "Marathi",
  maritalStatus: "Never Married",
  education: "B.Tech",
  occupation: "Full Stack Developer",
  city: "Nashik",
  state: "Maharashtra",
  bio: "Code by day, stargaze by night.",
  hobbies: ["Astronomy", "Coding", "Badminton"],
  favoriteFoods: ["Vada Pav", "Biryani"],
  favoriteColor: "Purple",
  interests: ["Science", "Technology", "Nature"],
  personalityType: "Introvert",
  height: 171,
  annualIncome: 1000000,
  drinking: "No",
  smoking: "No",
  languagesKnown: ["Marathi", "Hindi", "English"],
  partnerPreferences: { ageMin: 22, ageMax: 28, religions: ["Hindu"], cities: ["Nashik", "Pune"], occupations: ["Engineer", "Teacher"] }
},

{
  name: "Suresh Iyer",
  email: "suresh@gmail.com",
  phoneNumber: "9876543226",
  password: "123456",
  photos: ["https://images.unsplash.com/photo-1570295999919-56ceb5ecca61"],
  gender: "Male",
  dateOfBirth: "1993-06-14",
  religion: "Hindu",
  motherTongue: "Tamil",
  maritalStatus: "Never Married",
  education: "B.E",
  occupation: "Mechanical Engineer",
  city: "Coimbatore",
  state: "Tamil Nadu",
  bio: "Simple, honest and hardworking.",
  hobbies: ["Cricket", "Cooking", "Reading"],
  favoriteFoods: ["Sambar Rice", "Dosa"],
  favoriteColor: "Yellow",
  interests: ["Engineering", "Sports", "Nature"],
  personalityType: "Ambivert",
  height: 169,
  annualIncome: 900000,
  drinking: "No",
  smoking: "No",
  languagesKnown: ["Tamil", "English"],
  partnerPreferences: { ageMin: 22, ageMax: 29, religions: ["Hindu"], cities: ["Coimbatore", "Chennai"], occupations: ["Teacher", "Engineer"] }
},

{
  name: "Rahul Nair",
  email: "rahulnair@gmail.com",
  phoneNumber: "9876543227",
  password: "123456",
  photos: ["https://images.unsplash.com/photo-1552058544-f2b08422138a"],
  gender: "Male",
  dateOfBirth: "1996-02-28",
  religion: "Hindu",
  motherTongue: "Malayalam",
  maritalStatus: "Never Married",
  education: "MCA",
  occupation: "Software Developer",
  city: "Kochi",
  state: "Kerala",
  bio: "Kerala boy with big dreams.",
  hobbies: ["Football", "Music", "Travel"],
  favoriteFoods: ["Kerala Fish Curry", "Appam"],
  favoriteColor: "Green",
  interests: ["Technology", "Sports", "Travel"],
  personalityType: "Extrovert",
  height: 175,
  annualIncome: 1100000,
  drinking: "Occasionally",
  smoking: "No",
  languagesKnown: ["Malayalam", "English", "Hindi"],
  partnerPreferences: { ageMin: 22, ageMax: 29, religions: ["Hindu"], cities: ["Kochi", "Bangalore"], occupations: ["Engineer", "Nurse"] }
},

{
  name: "Farhan Sheikh",
  email: "farhan@gmail.com",
  phoneNumber: "9876543228",
  password: "123456",
  photos: ["https://images.unsplash.com/photo-1547425260-76bcadfb4f2c"],
  gender: "Male",
  dateOfBirth: "1995-10-10",
  religion: "Muslim",
  motherTongue: "Urdu",
  maritalStatus: "Never Married",
  education: "B.Tech",
  occupation: "Civil Engineer",
  city: "Lucknow",
  state: "Uttar Pradesh",
  bio: "Building bridges — literally and figuratively.",
  hobbies: ["Cricket", "Poetry", "Travel"],
  favoriteFoods: ["Biryani", "Kebab"],
  favoriteColor: "White",
  interests: ["Architecture", "Travel", "Literature"],
  personalityType: "Ambivert",
  height: 176,
  annualIncome: 950000,
  drinking: "No",
  smoking: "No",
  languagesKnown: ["Urdu", "Hindi", "English"],
  partnerPreferences: { ageMin: 22, ageMax: 29, religions: ["Muslim"], cities: ["Lucknow", "Delhi"], occupations: ["Teacher", "Doctor"] }
},

{
  name: "Imran Khan",
  email: "imran@gmail.com",
  phoneNumber: "9876543229",
  password: "123456",
  photos: ["https://images.unsplash.com/photo-1500048993953-d23a436266cf"],
  gender: "Male",
  dateOfBirth: "1994-05-05",
  religion: "Muslim",
  motherTongue: "Urdu",
  maritalStatus: "Never Married",
  education: "MBA",
  occupation: "Business Owner",
  city: "Mumbai",
  state: "Maharashtra",
  bio: "Entrepreneur with a love for family values.",
  hobbies: ["Gym", "Reading", "Football"],
  favoriteFoods: ["Nihari", "Biryani"],
  favoriteColor: "Black",
  interests: ["Business", "Sports", "Travel"],
  personalityType: "Extrovert",
  height: 181,
  annualIncome: 3000000,
  drinking: "No",
  smoking: "No",
  languagesKnown: ["Urdu", "Hindi", "English"],
  partnerPreferences: { ageMin: 22, ageMax: 30, religions: ["Muslim"], cities: ["Mumbai", "Hyderabad"], occupations: ["Doctor", "Teacher"] }
},

{
  name: "Rajesh Pillai",
  email: "rajesh@gmail.com",
  phoneNumber: "9876543230",
  password: "123456",
  photos: ["https://images.unsplash.com/photo-1504593811423-6dd665756598"],
  gender: "Male",
  dateOfBirth: "1992-11-17",
  religion: "Hindu",
  motherTongue: "Malayalam",
  maritalStatus: "Divorced",
  education: "MBA",
  occupation: "HR Manager",
  city: "Trivandrum",
  state: "Kerala",
  bio: "Looking for a fresh start with the right person.",
  hobbies: ["Reading", "Cooking", "Yoga"],
  favoriteFoods: ["Puttu", "Kadala Curry"],
  favoriteColor: "Blue",
  interests: ["Wellness", "Travel", "Business"],
  personalityType: "Introvert",
  height: 170,
  annualIncome: 1200000,
  drinking: "No",
  smoking: "No",
  languagesKnown: ["Malayalam", "English", "Tamil"],
  partnerPreferences: { ageMin: 25, ageMax: 35, religions: ["Hindu"], cities: ["Trivandrum", "Kochi"], occupations: ["Any"] }
},

{
  name: "Harpreet Singh",
  email: "harpreet@gmail.com",
  phoneNumber: "9876543231",
  password: "123456",
  photos: ["https://images.unsplash.com/photo-1531427186611-ecfd6d936c79"],
  gender: "Male",
  dateOfBirth: "1993-03-08",
  religion: "Sikh",
  motherTongue: "Punjabi",
  maritalStatus: "Never Married",
  education: "B.Com",
  occupation: "Business",
  city: "Amritsar",
  state: "Punjab",
  bio: "Proud Punjabi who values family above all.",
  hobbies: ["Bhangra", "Gym", "Farming"],
  favoriteFoods: ["Sarson Ka Saag", "Makke Di Roti"],
  favoriteColor: "Yellow",
  interests: ["Agriculture", "Sports", "Music"],
  personalityType: "Extrovert",
  height: 183,
  annualIncome: 1500000,
  drinking: "No",
  smoking: "No",
  languagesKnown: ["Punjabi", "Hindi", "English"],
  partnerPreferences: { ageMin: 22, ageMax: 29, religions: ["Sikh"], cities: ["Amritsar", "Chandigarh"], occupations: ["Any"] }
},

{
  name: "Deepak Gowda",
  email: "deepak@gmail.com",
  phoneNumber: "9876543232",
  password: "123456",
  photos: ["https://images.unsplash.com/photo-1492562080023-ab3db95bfbce"],
  gender: "Male",
  dateOfBirth: "1997-08-14",
  religion: "Hindu",
  motherTongue: "Kannada",
  maritalStatus: "Never Married",
  education: "B.Sc",
  occupation: "Data Analyst",
  city: "Bangalore",
  state: "Karnataka",
  bio: "Numbers tell stories — I translate them.",
  hobbies: ["Chess", "Cycling", "Cooking"],
  favoriteFoods: ["Bisi Bele Bath", "Pizza"],
  favoriteColor: "Teal",
  interests: ["Data", "Fitness", "Travel"],
  personalityType: "Introvert",
  height: 172,
  annualIncome: 1300000,
  drinking: "No",
  smoking: "No",
  languagesKnown: ["Kannada", "English", "Hindi"],
  partnerPreferences: { ageMin: 22, ageMax: 28, religions: ["Hindu"], cities: ["Bangalore", "Mysore"], occupations: ["Engineer", "Teacher"] }
},

{
  name: "Aakash Tiwari",
  email: "aakash@gmail.com",
  phoneNumber: "9876543233",
  password: "123456",
  photos: ["https://images.unsplash.com/photo-1519345182560-3f2917c472ef"],
  gender: "Male",
  dateOfBirth: "1998-06-20",
  religion: "Hindu",
  motherTongue: "Hindi",
  maritalStatus: "Never Married",
  education: "B.Tech",
  occupation: "Cloud Engineer",
  city: "Bhopal",
  state: "Madhya Pradesh",
  bio: "From Bhopal to the cloud — literally.",
  hobbies: ["Gaming", "Music", "Travel"],
  favoriteFoods: ["Poha", "Jalebi"],
  favoriteColor: "Blue",
  interests: ["Technology", "Music", "Gaming"],
  personalityType: "Ambivert",
  height: 174,
  annualIncome: 1100000,
  drinking: "No",
  smoking: "No",
  languagesKnown: ["Hindi", "English"],
  partnerPreferences: { ageMin: 22, ageMax: 28, religions: ["Hindu"], cities: ["Bhopal", "Indore"], occupations: ["Engineer", "Teacher"] }
},

{
  name: "Varun Reddy",
  email: "varun@gmail.com",
  phoneNumber: "9876543234",
  password: "123456",
  photos: ["https://images.unsplash.com/photo-1524638431109-93d95c968f03"],
  gender: "Male",
  dateOfBirth: "1996-09-03",
  religion: "Hindu",
  motherTongue: "Telugu",
  maritalStatus: "Never Married",
  education: "B.Tech",
  occupation: "Product Manager",
  city: "Hyderabad",
  state: "Telangana",
  bio: "Building products that matter.",
  hobbies: ["Reading", "Gym", "Badminton"],
  favoriteFoods: ["Biryani", "Burger"],
  favoriteColor: "Maroon",
  interests: ["Product", "Business", "Fitness"],
  personalityType: "Extrovert",
  height: 178,
  annualIncome: 2500000,
  drinking: "Occasionally",
  smoking: "No",
  languagesKnown: ["Telugu", "English", "Hindi"],
  partnerPreferences: { ageMin: 23, ageMax: 30, religions: ["Hindu"], cities: ["Hyderabad", "Bangalore"], occupations: ["Engineer", "Doctor"] }
},

{
  name: "Gaurav Jain",
  email: "gaurav@gmail.com",
  phoneNumber: "9876543235",
  password: "123456",
  photos: ["https://images.unsplash.com/photo-1506277886164-e25aa3f4ef7f"],
  gender: "Male",
  dateOfBirth: "1994-01-19",
  religion: "Jain",
  motherTongue: "Gujarati",
  maritalStatus: "Never Married",
  education: "CA",
  occupation: "Finance Analyst",
  city: "Surat",
  state: "Gujarat",
  bio: "Vegetarian, values-driven, family-first.",
  hobbies: ["Yoga", "Reading", "Travel"],
  favoriteFoods: ["Gujarati Thali", "Khichdi"],
  favoriteColor: "White",
  interests: ["Finance", "Wellness", "Travel"],
  personalityType: "Introvert",
  height: 170,
  annualIncome: 1800000,
  drinking: "No",
  smoking: "No",
  languagesKnown: ["Gujarati", "Hindi", "English"],
  partnerPreferences: { ageMin: 22, ageMax: 28, religions: ["Jain"], cities: ["Surat", "Ahmedabad"], occupations: ["Any"] }
},

{
  name: "Manish Dubey",
  email: "manish@gmail.com",
  phoneNumber: "9876543236",
  password: "123456",
  photos: ["https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91"],
  gender: "Male",
  dateOfBirth: "1995-07-07",
  religion: "Hindu",
  motherTongue: "Hindi",
  maritalStatus: "Never Married",
  education: "B.Tech",
  occupation: "Embedded Systems Engineer",
  city: "Lucknow",
  state: "Uttar Pradesh",
  bio: "Hardware meets software — that's my world.",
  hobbies: ["Electronics", "Badminton", "Music"],
  favoriteFoods: ["Tehri", "Kebab"],
  favoriteColor: "Green",
  interests: ["Technology", "Science", "Sports"],
  personalityType: "Introvert",
  height: 173,
  annualIncome: 1000000,
  drinking: "No",
  smoking: "No",
  languagesKnown: ["Hindi", "English"],
  partnerPreferences: { ageMin: 22, ageMax: 29, religions: ["Hindu"], cities: ["Lucknow", "Kanpur"], occupations: ["Engineer", "Teacher"] }
},

{
  name: "Anand Krishnamurthy",
  email: "anand@gmail.com",
  phoneNumber: "9876543237",
  password: "123456",
  photos: ["https://images.unsplash.com/photo-1534614971-6be99a7a3ffd"],
  gender: "Male",
  dateOfBirth: "1993-04-22",
  religion: "Hindu",
  motherTongue: "Tamil",
  maritalStatus: "Never Married",
  education: "PhD",
  occupation: "Research Scientist",
  city: "Chennai",
  state: "Tamil Nadu",
  bio: "Scientist by profession, philosopher by passion.",
  hobbies: ["Reading", "Chess", "Classical Music"],
  favoriteFoods: ["Curd Rice", "Rasam"],
  favoriteColor: "Saffron",
  interests: ["Science", "Philosophy", "Music"],
  personalityType: "Introvert",
  height: 168,
  annualIncome: 1400000,
  drinking: "No",
  smoking: "No",
  languagesKnown: ["Tamil", "English", "Sanskrit"],
  partnerPreferences: { ageMin: 24, ageMax: 31, religions: ["Hindu"], cities: ["Chennai", "Bangalore"], occupations: ["Doctor", "Researcher"] }
},

{
  name: "Ravi Shankar",
  email: "ravi@gmail.com",
  phoneNumber: "9876543238",
  password: "123456",
  photos: ["https://images.unsplash.com/photo-1522075469751-3a6694fb2f61"],
  gender: "Male",
  dateOfBirth: "1996-10-30",
  religion: "Hindu",
  motherTongue: "Kannada",
  maritalStatus: "Never Married",
  education: "B.Tech",
  occupation: "Game Developer",
  city: "Bangalore",
  state: "Karnataka",
  bio: "Life's a game — I help design it.",
  hobbies: ["Gaming", "Anime", "Cycling"],
  favoriteFoods: ["Ragi Mudde", "Pizza"],
  favoriteColor: "Purple",
  interests: ["Gaming", "Animation", "Technology"],
  personalityType: "Introvert",
  height: 171,
  annualIncome: 1200000,
  drinking: "No",
  smoking: "No",
  languagesKnown: ["Kannada", "English"],
  partnerPreferences: { ageMin: 22, ageMax: 28, religions: ["Hindu"], cities: ["Bangalore", "Mysore"], occupations: ["Engineer", "Designer"] }
},

{
  name: "Tarun Bose",
  email: "tarun@gmail.com",
  phoneNumber: "9876543239",
  password: "123456",
  photos: ["https://images.unsplash.com/photo-1540569014015-19a7be504e3a"],
  gender: "Male",
  dateOfBirth: "1994-08-08",
  religion: "Hindu",
  motherTongue: "Bengali",
  maritalStatus: "Never Married",
  education: "MBA",
  occupation: "Operations Manager",
  city: "Kolkata",
  state: "West Bengal",
  bio: "Organized, reliable, and loves a good debate.",
  hobbies: ["Football", "Reading", "Cooking"],
  favoriteFoods: ["Macher Jhol", "Rosogolla"],
  favoriteColor: "White",
  interests: ["Business", "Sports", "Literature"],
  personalityType: "Extrovert",
  height: 177,
  annualIncome: 1600000,
  drinking: "Occasionally",
  smoking: "No",
  languagesKnown: ["Bengali", "Hindi", "English"],
  partnerPreferences: { ageMin: 23, ageMax: 30, religions: ["Hindu"], cities: ["Kolkata", "Mumbai"], occupations: ["Manager", "Doctor"] }
},

{
  name: "Yash Kapoor",
  email: "yash@gmail.com",
  phoneNumber: "9876543240",
  password: "123456",
  photos: ["https://images.unsplash.com/photo-1548544149-4835e62ee5b3"],
  gender: "Male",
  dateOfBirth: "1997-02-15",
  religion: "Hindu",
  motherTongue: "Hindi",
  maritalStatus: "Never Married",
  education: "BBA",
  occupation: "Digital Marketer",
  city: "Jaipur",
  state: "Rajasthan",
  bio: "Creative soul from the pink city.",
  hobbies: ["Photography", "Travel", "Music"],
  favoriteFoods: ["Dal Baati", "Lassi"],
  favoriteColor: "Pink",
  interests: ["Marketing", "Travel", "Art"],
  personalityType: "Extrovert",
  height: 175,
  annualIncome: 800000,
  drinking: "No",
  smoking: "No",
  languagesKnown: ["Hindi", "English", "Rajasthani"],
  partnerPreferences: { ageMin: 22, ageMax: 28, religions: ["Hindu"], cities: ["Jaipur", "Delhi"], occupations: ["Any"] }
},

{
  name: "Ajay Pandey",
  email: "ajay@gmail.com",
  phoneNumber: "9876543241",
  password: "123456",
  photos: ["https://images.unsplash.com/photo-1521572163474-6864f9cf17ab"],
  gender: "Male",
  dateOfBirth: "1995-05-25",
  religion: "Hindu",
  motherTongue: "Hindi",
  maritalStatus: "Never Married",
  education: "MBBS",
  occupation: "Doctor",
  city: "Varanasi",
  state: "Uttar Pradesh",
  bio: "Healing people, one day at a time.",
  hobbies: ["Yoga", "Reading", "Swimming"],
  favoriteFoods: ["Kachori", "Lassi"],
  favoriteColor: "White",
  interests: ["Medicine", "Wellness", "Spirituality"],
  personalityType: "Ambivert",
  height: 176,
  annualIncome: 1800000,
  drinking: "No",
  smoking: "No",
  languagesKnown: ["Hindi", "English"],
  partnerPreferences: { ageMin: 23, ageMax: 30, religions: ["Hindu"], cities: ["Varanasi", "Lucknow"], occupations: ["Doctor", "Teacher"] }
},

{
  name: "Kabir Das",
  email: "kabir@gmail.com",
  phoneNumber: "9876543242",
  password: "123456",
  photos: ["https://images.unsplash.com/photo-1506440305673-5f1d3eda1869"],
  gender: "Male",
  dateOfBirth: "1993-12-12",
  religion: "Muslim",
  motherTongue: "Hindi",
  maritalStatus: "Never Married",
  education: "LLB",
  occupation: "Lawyer",
  city: "Delhi",
  state: "Delhi",
  bio: "Justice seeker with a calm mind.",
  hobbies: ["Reading", "Debating", "Travel"],
  favoriteFoods: ["Kebab", "Biryani"],
  favoriteColor: "Black",
  interests: ["Law", "Politics", "Literature"],
  personalityType: "Ambivert",
  height: 179,
  annualIncome: 2000000,
  drinking: "No",
  smoking: "No",
  languagesKnown: ["Hindi", "English", "Urdu"],
  partnerPreferences: { ageMin: 24, ageMax: 32, religions: ["Muslim"], cities: ["Delhi", "Mumbai"], occupations: ["Doctor", "Teacher"] }
},

{
  name: "Sandeep Chatterjee",
  email: "sandeep@gmail.com",
  phoneNumber: "9876543243",
  password: "123456",
  photos: ["https://images.unsplash.com/photo-1472099645785-5658abf4ff4e"],
  gender: "Male",
  dateOfBirth: "1992-03-03",
  religion: "Hindu",
  motherTongue: "Bengali",
  maritalStatus: "Never Married",
  education: "M.Sc",
  occupation: "Professor",
  city: "Kolkata",
  state: "West Bengal",
  bio: "Passion for knowledge and literature.",
  hobbies: ["Writing", "Teaching", "Classical Music"],
  favoriteFoods: ["Hilsa Fish", "Mishti Doi"],
  favoriteColor: "Cream",
  interests: ["Education", "Literature", "Science"],
  personalityType: "Introvert",
  height: 167,
  annualIncome: 1000000,
  drinking: "Occasionally",
  smoking: "No",
  languagesKnown: ["Bengali", "Hindi", "English"],
  partnerPreferences: { ageMin: 24, ageMax: 32, religions: ["Hindu"], cities: ["Kolkata", "Delhi"], occupations: ["Teacher", "Researcher"] }
},

{
  name: "Vivek Menon",
  email: "vivek@gmail.com",
  phoneNumber: "9876543244",
  password: "123456",
  photos: ["https://images.unsplash.com/photo-1480455624313-e29b44bbfde1"],
  gender: "Male",
  dateOfBirth: "1996-07-27",
  religion: "Hindu",
  motherTongue: "Malayalam",
  maritalStatus: "Never Married",
  education: "B.Tech",
  occupation: "Cybersecurity Analyst",
  city: "Kochi",
  state: "Kerala",
  bio: "Keeping the internet safe, one firewall at a time.",
  hobbies: ["Hacking CTFs", "Swimming", "Music"],
  favoriteFoods: ["Prawn Curry", "Appam"],
  favoriteColor: "Dark Green",
  interests: ["Cybersecurity", "Technology", "Music"],
  personalityType: "Introvert",
  height: 174,
  annualIncome: 1700000,
  drinking: "No",
  smoking: "No",
  languagesKnown: ["Malayalam", "English", "Hindi"],
  partnerPreferences: { ageMin: 22, ageMax: 29, religions: ["Hindu"], cities: ["Kochi", "Bangalore"], occupations: ["Engineer", "Doctor"] }
},

{
  name: "Naveen Yadav",
  email: "naveen@gmail.com",
  phoneNumber: "9876543245",
  password: "123456",
  photos: ["https://images.unsplash.com/photo-1527980965255-d3b416303d12"],
  gender: "Male",
  dateOfBirth: "1997-11-11",
  religion: "Hindu",
  motherTongue: "Hindi",
  maritalStatus: "Never Married",
  education: "B.Tech",
  occupation: "IoT Developer",
  city: "Agra",
  state: "Uttar Pradesh",
  bio: "Smart home enthusiast from the city of Taj.",
  hobbies: ["Robotics", "Cricket", "Photography"],
  favoriteFoods: ["Petha", "Biryani"],
  favoriteColor: "Orange",
  interests: ["IoT", "Technology", "Travel"],
  personalityType: "Ambivert",
  height: 172,
  annualIncome: 950000,
  drinking: "No",
  smoking: "No",
  languagesKnown: ["Hindi", "English"],
  partnerPreferences: { ageMin: 22, ageMax: 28, religions: ["Hindu"], cities: ["Agra", "Delhi"], occupations: ["Engineer", "Teacher"] }
},

// Continue males...
{
  name: "Sanjay Bhatt",
  email: "sanjay@gmail.com",
  phoneNumber: "9876543246",
  password: "123456",
  photos: ["https://images.unsplash.com/photo-1488161628813-04466f872be2"],
  gender: "Male",
  dateOfBirth: "1994-04-04",
  religion: "Hindu",
  motherTongue: "Hindi",
  maritalStatus: "Never Married",
  education: "B.Arch",
  occupation: "Architect",
  city: "Ahmedabad",
  state: "Gujarat",
  bio: "I design spaces that become memories.",
  hobbies: ["Sketching", "Travel", "Yoga"],
  favoriteFoods: ["Thepla", "Dal Makhani"],
  favoriteColor: "Ivory",
  interests: ["Architecture", "Art", "Travel"],
  personalityType: "Introvert",
  height: 175,
  annualIncome: 1300000,
  drinking: "No",
  smoking: "No",
  languagesKnown: ["Hindi", "Gujarati", "English"],
  partnerPreferences: { ageMin: 23, ageMax: 30, religions: ["Hindu"], cities: ["Ahmedabad", "Mumbai"], occupations: ["Designer", "Engineer"] }
},

{
  name: "Ashwin Balaji",
  email: "ashwin@gmail.com",
  phoneNumber: "9876543247",
  password: "123456",
  photos: ["https://images.unsplash.com/photo-1539571696357-5a69c17a67c6"],
  gender: "Male",
  dateOfBirth: "1995-01-01",
  religion: "Hindu",
  motherTongue: "Tamil",
  maritalStatus: "Never Married",
  education: "B.Tech",
  occupation: "Mobile Developer",
  city: "Madurai",
  state: "Tamil Nadu",
  bio: "Apps that make life simpler.",
  hobbies: ["Jallikattu", "Cooking", "Gaming"],
  favoriteFoods: ["Kari Dosa", "Parotta"],
  favoriteColor: "Red",
  interests: ["Technology", "Culture", "Food"],
  personalityType: "Extrovert",
  height: 170,
  annualIncome: 1050000,
  drinking: "No",
  smoking: "No",
  languagesKnown: ["Tamil", "English"],
  partnerPreferences: { ageMin: 22, ageMax: 29, religions: ["Hindu"], cities: ["Madurai", "Chennai"], occupations: ["Engineer", "Teacher"] }
},

{
  name: "Mohit Arora",
  email: "mohit@gmail.com",
  phoneNumber: "9876543248",
  password: "123456",
  photos: ["https://images.unsplash.com/photo-1534337621606-e3df5ee0e97f"],
  gender: "Male",
  dateOfBirth: "1998-09-09",
  religion: "Hindu",
  motherTongue: "Punjabi",
  maritalStatus: "Never Married",
  education: "B.Tech",
  occupation: "Blockchain Developer",
  city: "Chandigarh",
  state: "Punjab",
  bio: "Decentralizing the future.",
  hobbies: ["Gym", "Crypto", "Music"],
  favoriteFoods: ["Makke Di Roti", "Tandoori Chicken"],
  favoriteColor: "Gold",
  interests: ["Blockchain", "Finance", "Fitness"],
  personalityType: "Extrovert",
  height: 180,
  annualIncome: 1800000,
  drinking: "Occasionally",
  smoking: "No",
  languagesKnown: ["Punjabi", "Hindi", "English"],
  partnerPreferences: { ageMin: 22, ageMax: 28, religions: ["Hindu", "Sikh"], cities: ["Chandigarh", "Delhi"], occupations: ["Engineer", "Doctor"] }
},

{
  name: "Lokesh Naidu",
  email: "lokesh@gmail.com",
  phoneNumber: "9876543249",
  password: "123456",
  photos: ["https://images.unsplash.com/photo-1560250097-0b93528c311a"],
  gender: "Male",
  dateOfBirth: "1996-06-16",
  religion: "Hindu",
  motherTongue: "Telugu",
  maritalStatus: "Never Married",
  education: "B.Tech",
  occupation: "Network Engineer",
  city: "Vijayawada",
  state: "Andhra Pradesh",
  bio: "Connecting the world, starting from Andhra.",
  hobbies: ["Kabaddi", "Cooking", "Travel"],
  favoriteFoods: ["Pesarattu", "Gongura Chicken"],
  favoriteColor: "Blue",
  interests: ["Networking", "Sports", "Travel"],
  personalityType: "Ambivert",
  height: 173,
  annualIncome: 900000,
  drinking: "No",
  smoking: "No",
  languagesKnown: ["Telugu", "English", "Hindi"],
  partnerPreferences: { ageMin: 22, ageMax: 28, religions: ["Hindu"], cities: ["Vijayawada", "Hyderabad"], occupations: ["Engineer", "Teacher"] }
},

{
  name: "Rahul Thomas",
  email: "rahulthomas@gmail.com",
  phoneNumber: "9876543250",
  password: "123456",
  photos: ["https://images.unsplash.com/photo-1543132220-4bf3de6e10ae"],
  gender: "Male",
  dateOfBirth: "1994-03-15",
  religion: "Christian",
  motherTongue: "Malayalam",
  maritalStatus: "Never Married",
  education: "B.Tech",
  occupation: "System Administrator",
  city: "Kottayam",
  state: "Kerala",
  bio: "Faith, family, and football.",
  hobbies: ["Football", "Church Choir", "Travel"],
  favoriteFoods: ["Beef Fry", "Appam"],
  favoriteColor: "Blue",
  interests: ["Technology", "Sports", "Faith"],
  personalityType: "Extrovert",
  height: 176,
  annualIncome: 1000000,
  drinking: "Occasionally",
  smoking: "No",
  languagesKnown: ["Malayalam", "English", "Tamil"],
  partnerPreferences: { ageMin: 22, ageMax: 29, religions: ["Christian"], cities: ["Kottayam", "Kochi"], occupations: ["Engineer", "Nurse"] }
},

{
  name: "Dinesh Babu",
  email: "dinesh@gmail.com",
  phoneNumber: "9876543251",
  password: "123456",
  photos: ["https://images.unsplash.com/photo-1555952517-2e8e729e0b44"],
  gender: "Male",
  dateOfBirth: "1995-12-25",
  religion: "Hindu",
  motherTongue: "Tamil",
  maritalStatus: "Never Married",
  education: "B.E",
  occupation: "Electrical Engineer",
  city: "Salem",
  state: "Tamil Nadu",
  bio: "Powering the world, one circuit at a time.",
  hobbies: ["Volleyball", "Cooking", "Gardening"],
  favoriteFoods: ["Pongal", "Idli"],
  favoriteColor: "Green",
  interests: ["Engineering", "Nature", "Sports"],
  personalityType: "Ambivert",
  height: 168,
  annualIncome: 850000,
  drinking: "No",
  smoking: "No",
  languagesKnown: ["Tamil", "English"],
  partnerPreferences: { ageMin: 22, ageMax: 29, religions: ["Hindu"], cities: ["Salem", "Chennai"], occupations: ["Teacher", "Engineer"] }
},

{
  name: "Kartik Bhardwaj",
  email: "kartik@gmail.com",
  phoneNumber: "9876543252",
  password: "123456",
  photos: ["https://images.unsplash.com/photo-1501196354995-cbb51c65aaea"],
  gender: "Male",
  dateOfBirth: "1997-04-04",
  religion: "Hindu",
  motherTongue: "Hindi",
  maritalStatus: "Never Married",
  education: "B.Tech",
  occupation: "QA Engineer",
  city: "Noida",
  state: "Uttar Pradesh",
  bio: "Quality is not an act, it is a habit.",
  hobbies: ["Cricket", "Gym", "Music"],
  favoriteFoods: ["Chole Bhature", "Pasta"],
  favoriteColor: "Navy Blue",
  interests: ["Technology", "Sports", "Music"],
  personalityType: "Introvert",
  height: 175,
  annualIncome: 1100000,
  drinking: "No",
  smoking: "No",
  languagesKnown: ["Hindi", "English"],
  partnerPreferences: { ageMin: 22, ageMax: 28, religions: ["Hindu"], cities: ["Noida", "Delhi"], occupations: ["Engineer", "Teacher"] }
},

{
  name: "Pradeep Nambiar",
  email: "pradeep@gmail.com",
  phoneNumber: "9876543253",
  password: "123456",
  photos: ["https://images.unsplash.com/photo-1516914943479-89db7d9ae7f2"],
  gender: "Male",
  dateOfBirth: "1993-08-18",
  religion: "Hindu",
  motherTongue: "Malayalam",
  maritalStatus: "Never Married",
  education: "MBA",
  occupation: "Supply Chain Manager",
  city: "Kozhikode",
  state: "Kerala",
  bio: "Logistics wizard from God's own country.",
  hobbies: ["Badminton", "Cooking", "Reading"],
  favoriteFoods: ["Malabar Biryani", "Pathiri"],
  favoriteColor: "Brown",
  interests: ["Business", "Travel", "Food"],
  personalityType: "Extrovert",
  height: 174,
  annualIncome: 1400000,
  drinking: "No",
  smoking: "No",
  languagesKnown: ["Malayalam", "English", "Tamil"],
  partnerPreferences: { ageMin: 24, ageMax: 31, religions: ["Hindu"], cities: ["Kozhikode", "Kochi"], occupations: ["Any"] }
},

{
  name: "Shyam Sundar",
  email: "shyam@gmail.com",
  phoneNumber: "9876543254",
  password: "123456",
  photos: ["https://images.unsplash.com/photo-1490195117352-aa267f47f2d5"],
  gender: "Male",
  dateOfBirth: "1996-03-21",
  religion: "Hindu",
  motherTongue: "Odia",
  maritalStatus: "Never Married",
  education: "B.Tech",
  occupation: "Software Engineer",
  city: "Bhubaneswar",
  state: "Odisha",
  bio: "Proud Odia with a global mindset.",
  hobbies: ["Dandiya", "Coding", "Travel"],
  favoriteFoods: ["Dalma", "Pakhala"],
  favoriteColor: "Saffron",
  interests: ["Technology", "Culture", "Travel"],
  personalityType: "Ambivert",
  height: 172,
  annualIncome: 1000000,
  drinking: "No",
  smoking: "No",
  languagesKnown: ["Odia", "Hindi", "English"],
  partnerPreferences: { ageMin: 22, ageMax: 29, religions: ["Hindu"], cities: ["Bhubaneswar", "Kolkata"], occupations: ["Engineer", "Teacher"] }
},

{
  name: "Akash Gupta",
  email: "akashg@gmail.com",
  phoneNumber: "9876543255",
  password: "123456",
  photos: ["https://images.unsplash.com/photo-1492562080023-ab3db95bfbce"],
  gender: "Male",
  dateOfBirth: "1998-01-10",
  religion: "Hindu",
  motherTongue: "Hindi",
  maritalStatus: "Never Married",
  education: "B.Tech",
  occupation: "React Developer",
  city: "Gurgaon",
  state: "Haryana",
  bio: "Building UIs that users love.",
  hobbies: ["Gaming", "Travel", "Cooking"],
  favoriteFoods: ["Biryani", "Momos"],
  favoriteColor: "Cyan",
  interests: ["Technology", "Gaming", "Travel"],
  personalityType: "Introvert",
  height: 173,
  annualIncome: 1300000,
  drinking: "No",
  smoking: "No",
  languagesKnown: ["Hindi", "English"],
  partnerPreferences: { ageMin: 22, ageMax: 28, religions: ["Hindu"], cities: ["Gurgaon", "Delhi"], occupations: ["Engineer", "Any"] }
},

{
  name: "Vinay Kumar",
  email: "vinay@gmail.com",
  phoneNumber: "9876543256",
  password: "123456",
  photos: ["https://images.unsplash.com/photo-1506794778202-cad84cf45f1d"],
  gender: "Male",
  dateOfBirth: "1994-07-19",
  religion: "Hindu",
  motherTongue: "Kannada",
  maritalStatus: "Never Married",
  education: "M.Tech",
  occupation: "VLSI Engineer",
  city: "Bangalore",
  state: "Karnataka",
  bio: "Chips and circuits are my language.",
  hobbies: ["Chess", "Trekking", "Music"],
  favoriteFoods: ["Jolada Rotti", "Biryani"],
  favoriteColor: "Dark Blue",
  interests: ["Electronics", "Science", "Nature"],
  personalityType: "Introvert",
  height: 170,
  annualIncome: 1600000,
  drinking: "No",
  smoking: "No",
  languagesKnown: ["Kannada", "English", "Hindi"],
  partnerPreferences: { ageMin: 23, ageMax: 30, religions: ["Hindu"], cities: ["Bangalore", "Mysore"], occupations: ["Engineer", "Doctor"] }
},

{
  name: "Saurabh Mishra",
  email: "saurabh@gmail.com",
  phoneNumber: "9876543257",
  password: "123456",
  photos: ["https://images.unsplash.com/photo-1519345182560-3f2917c472ef"],
  gender: "Male",
  dateOfBirth: "1993-11-22",
  religion: "Hindu",
  motherTongue: "Hindi",
  maritalStatus: "Never Married",
  education: "IAS",
  occupation: "Civil Servant",
  city: "Allahabad",
  state: "Uttar Pradesh",
  bio: "Serving the nation with pride.",
  hobbies: ["Reading", "Running", "Debating"],
  favoriteFoods: ["Tehri", "Samosa"],
  favoriteColor: "White",
  interests: ["Governance", "Literature", "Sports"],
  personalityType: "Ambivert",
  height: 178,
  annualIncome: 1200000,
  drinking: "No",
  smoking: "No",
  languagesKnown: ["Hindi", "English", "Sanskrit"],
  partnerPreferences: { ageMin: 24, ageMax: 31, religions: ["Hindu"], cities: ["Allahabad", "Lucknow"], occupations: ["Doctor", "Teacher"] }
},

{
  name: "Rohit Shetty",
  email: "rohitshetty@gmail.com",
  phoneNumber: "9876543258",
  password: "123456",
  photos: ["https://images.unsplash.com/photo-1537511446984-935f663eb1f4"],
  gender: "Male",
  dateOfBirth: "1995-02-14",
  religion: "Hindu",
  motherTongue: "Tulu",
  maritalStatus: "Never Married",
  education: "B.Com",
  occupation: "Hotel Manager",
  city: "Mangalore",
  state: "Karnataka",
  bio: "Hospitality is my heart language.",
  hobbies: ["Cooking", "Travel", "Swimming"],
  favoriteFoods: ["Neer Dosa", "Fish Curry"],
  favoriteColor: "Sea Blue",
  interests: ["Hospitality", "Travel", "Food"],
  personalityType: "Extrovert",
  height: 174,
  annualIncome: 900000,
  drinking: "Occasionally",
  smoking: "No",
  languagesKnown: ["Tulu", "Kannada", "English"],
  partnerPreferences: { ageMin: 22, ageMax: 29, religions: ["Hindu"], cities: ["Mangalore", "Bangalore"], occupations: ["Any"] }
},

{
  name: "Rajan Pillai",
  email: "rajan@gmail.com",
  phoneNumber: "9876543259",
  password: "123456",
  photos: ["https://images.unsplash.com/photo-1500048993953-d23a436266cf"],
  gender: "Male",
  dateOfBirth: "1992-06-06",
  religion: "Hindu",
  motherTongue: "Malayalam",
  maritalStatus: "Divorced",
  education: "MBA",
  occupation: "Finance Manager",
  city: "Pune",
  state: "Maharashtra",
  bio: "Second chances are beautiful.",
  hobbies: ["Yoga", "Travel", "Reading"],
  favoriteFoods: ["Sadya", "Pasta"],
  favoriteColor: "Olive",
  interests: ["Finance", "Wellness", "Travel"],
  personalityType: "Introvert",
  height: 171,
  annualIncome: 1700000,
  drinking: "No",
  smoking: "No",
  languagesKnown: ["Malayalam", "English", "Hindi"],
  partnerPreferences: { ageMin: 26, ageMax: 36, religions: ["Hindu"], cities: ["Pune", "Mumbai"], occupations: ["Any"] }
},

{
  name: "Chetan Patil",
  email: "chetan@gmail.com",
  phoneNumber: "9876543260",
  password: "123456",
  photos: ["https://images.unsplash.com/photo-1472099645785-5658abf4ff4e"],
  gender: "Male",
  dateOfBirth: "1997-09-09",
  religion: "Hindu",
  motherTongue: "Marathi",
  maritalStatus: "Never Married",
  education: "B.Tech",
  occupation: "Machine Learning Engineer",
  city: "Kolhapur",
  state: "Maharashtra",
  bio: "Teaching machines to think.",
  hobbies: ["Kabaddi", "Music", "Coding"],
  favoriteFoods: ["Tambda Rassa", "Biryani"],
  favoriteColor: "Dark Red",
  interests: ["AI", "Sports", "Music"],
  personalityType: "Ambivert",
  height: 176,
  annualIncome: 1900000,
  drinking: "No",
  smoking: "No",
  languagesKnown: ["Marathi", "Hindi", "English"],
  partnerPreferences: { ageMin: 22, ageMax: 29, religions: ["Hindu"], cities: ["Kolhapur", "Pune"], occupations: ["Engineer", "Doctor"] }
},

{
  name: "Neeraj Chauhan",
  email: "neeraj@gmail.com",
  phoneNumber: "9876543261",
  password: "123456",
  photos: ["https://images.unsplash.com/photo-1547425260-76bcadfb4f2c"],
  gender: "Male",
  dateOfBirth: "1996-05-05",
  religion: "Hindu",
  motherTongue: "Hindi",
  maritalStatus: "Never Married",
  education: "BCA",
  occupation: "Web Developer",
  city: "Dehradun",
  state: "Uttarakhand",
  bio: "Mountains and code — that's my life.",
  hobbies: ["Trekking", "Photography", "Gaming"],
  favoriteFoods: ["Aloo Ke Gutke", "Kafuli"],
  favoriteColor: "Forest Green",
  interests: ["Technology", "Nature", "Photography"],
  personalityType: "Introvert",
  height: 174,
  annualIncome: 800000,
  drinking: "No",
  smoking: "No",
  languagesKnown: ["Hindi", "English", "Garhwali"],
  partnerPreferences: { ageMin: 22, ageMax: 28, religions: ["Hindu"], cities: ["Dehradun", "Delhi"], occupations: ["Engineer", "Teacher"] }
},

{
  name: "Prakash Babu",
  email: "prakash@gmail.com",
  phoneNumber: "9876543262",
  password: "123456",
  photos: ["https://images.unsplash.com/photo-1480455624313-e29b44bbfde1"],
  gender: "Male",
  dateOfBirth: "1993-01-26",
  religion: "Hindu",
  motherTongue: "Telugu",
  maritalStatus: "Never Married",
  education: "MBBS",
  occupation: "Surgeon",
  city: "Visakhapatnam",
  state: "Andhra Pradesh",
  bio: "Every surgery is a new story.",
  hobbies: ["Reading", "Swimming", "Yoga"],
  favoriteFoods: ["Biryani", "Pulihora"],
  favoriteColor: "White",
  interests: ["Medicine", "Science", "Fitness"],
  personalityType: "Introvert",
  height: 177,
  annualIncome: 3500000,
  drinking: "No",
  smoking: "No",
  languagesKnown: ["Telugu", "English", "Hindi"],
  partnerPreferences: { ageMin: 24, ageMax: 32, religions: ["Hindu"], cities: ["Visakhapatnam", "Hyderabad"], occupations: ["Doctor", "Engineer"] }
},

{
  name: "Anirudh Krishnan",
  email: "anirudh@gmail.com",
  phoneNumber: "9876543263",
  password: "123456",
  photos: ["https://images.unsplash.com/photo-1534614971-6be99a7a3ffd"],
  gender: "Male",
  dateOfBirth: "1997-07-07",
  religion: "Hindu",
  motherTongue: "Tamil",
  maritalStatus: "Never Married",
  education: "B.Tech",
  occupation: "Music Composer",
  city: "Chennai",
  state: "Tamil Nadu",
  bio: "Composing emotions into melodies.",
  hobbies: ["Music", "Travel", "Yoga"],
  favoriteFoods: ["Biryani", "Chettinad Curry"],
  favoriteColor: "Black",
  interests: ["Music", "Art", "Culture"],
  personalityType: "Introvert",
  height: 171,
  annualIncome: 1500000,
  drinking: "No",
  smoking: "No",
  languagesKnown: ["Tamil", "English"],
  partnerPreferences: { ageMin: 22, ageMax: 29, religions: ["Hindu"], cities: ["Chennai", "Bangalore"], occupations: ["Any"] }
},

{
  name: "Nitin Saxena",
  email: "nitin@gmail.com",
  phoneNumber: "9876543264",
  password: "123456",
  photos: ["https://images.unsplash.com/photo-1570295999919-56ceb5ecca61"],
  gender: "Male",
  dateOfBirth: "1994-10-10",
  religion: "Hindu",
  motherTongue: "Hindi",
  maritalStatus: "Never Married",
  education: "MBA",
  occupation: "Sales Director",
  city: "Indore",
  state: "Madhya Pradesh",
  bio: "Closing deals and opening hearts.",
  hobbies: ["Cricket", "Music", "Travel"],
  favoriteFoods: ["Poha Jalebi", "Biryani"],
  favoriteColor: "Maroon",
  interests: ["Sales", "Business", "Travel"],
  personalityType: "Extrovert",
  height: 179,
  annualIncome: 2200000,
  drinking: "Occasionally",
  smoking: "No",
  languagesKnown: ["Hindi", "English"],
  partnerPreferences: { ageMin: 23, ageMax: 30, religions: ["Hindu"], cities: ["Indore", "Mumbai"], occupations: ["Any"] }
},

{
  name: "Suraj Malhotra",
  email: "suraj@gmail.com",
  phoneNumber: "9876543265",
  password: "123456",
  photos: ["https://images.unsplash.com/photo-1552058544-f2b08422138a"],
  gender: "Male",
  dateOfBirth: "1998-08-28",
  religion: "Hindu",
  motherTongue: "Punjabi",
  maritalStatus: "Never Married",
  education: "B.Tech",
  occupation: "AR/VR Developer",
  city: "Ludhiana",
  state: "Punjab",
  bio: "Living in reality while building virtual worlds.",
  hobbies: ["VR Gaming", "Gym", "Cooking"],
  favoriteFoods: ["Butter Chicken", "Naan"],
  favoriteColor: "Electric Blue",
  interests: ["Technology", "Gaming", "Fitness"],
  personalityType: "Extrovert",
  height: 182,
  annualIncome: 1700000,
  drinking: "No",
  smoking: "No",
  languagesKnown: ["Punjabi", "Hindi", "English"],
  partnerPreferences: { ageMin: 22, ageMax: 28, religions: ["Hindu", "Sikh"], cities: ["Ludhiana", "Chandigarh"], occupations: ["Engineer", "Doctor"] }
},

{
  name: "Ramesh Achari",
  email: "ramesh@gmail.com",
  phoneNumber: "9876543266",
  password: "123456",
  photos: ["https://images.unsplash.com/photo-1560250097-0b93528c311a"],
  gender: "Male",
  dateOfBirth: "1991-03-30",
  religion: "Hindu",
  motherTongue: "Kannada",
  maritalStatus: "Divorced",
  education: "MBA",
  occupation: "Restaurant Owner",
  city: "Hubli",
  state: "Karnataka",
  bio: "Food entrepreneur looking for the right partner.",
  hobbies: ["Cooking", "Travel", "Music"],
  favoriteFoods: ["Kadubu", "Mutton Biryani"],
  favoriteColor: "Chocolate",
  interests: ["Food", "Business", "Travel"],
  personalityType: "Extrovert",
  height: 173,
  annualIncome: 2800000,
  drinking: "Occasionally",
  smoking: "No",
  languagesKnown: ["Kannada", "Hindi", "English"],
  partnerPreferences: { ageMin: 26, ageMax: 36, religions: ["Hindu"], cities: ["Hubli", "Bangalore"], occupations: ["Any"] }
},

{
  name: "Aryan Kapoor",
  email: "aryan@gmail.com",
  phoneNumber: "9876543267",
  password: "123456",
  photos: ["https://images.unsplash.com/photo-1531427186611-ecfd6d936c79"],
  gender: "Male",
  dateOfBirth: "1999-12-31",
  religion: "Hindu",
  motherTongue: "Hindi",
  maritalStatus: "Never Married",
  education: "B.Tech",
  occupation: "Fresher",
  city: "Delhi",
  state: "Delhi",
  bio: "Just started my journey — looking for my person.",
  hobbies: ["Travel", "Music", "Cricket"],
  favoriteFoods: ["Biryani", "Pav Bhaji"],
  favoriteColor: "Sky Blue",
  interests: ["Technology", "Music", "Sports"],
  personalityType: "Ambivert",
  height: 178,
  annualIncome: 500000,
  drinking: "No",
  smoking: "No",
  languagesKnown: ["Hindi", "English"],
  partnerPreferences: { ageMin: 21, ageMax: 27, religions: ["Hindu"], cities: ["Delhi", "Noida"], occupations: ["Any"] }
},

{
  name: "Paresh Shah",
  email: "paresh@gmail.com",
  phoneNumber: "9876543268",
  password: "123456",
  photos: ["https://images.unsplash.com/photo-1504593811423-6dd665756598"],
  gender: "Male",
  dateOfBirth: "1992-07-07",
  religion: "Jain",
  motherTongue: "Gujarati",
  maritalStatus: "Never Married",
  education: "B.Com",
  occupation: "Diamond Merchant",
  city: "Surat",
  state: "Gujarat",
  bio: "Shining bright from the diamond city.",
  hobbies: ["Business", "Travel", "Meditation"],
  favoriteFoods: ["Undhiyu", "Fafda"],
  favoriteColor: "Diamond White",
  interests: ["Business", "Spirituality", "Travel"],
  personalityType: "Introvert",
  height: 169,
  annualIncome: 5000000,
  drinking: "No",
  smoking: "No",
  languagesKnown: ["Gujarati", "Hindi", "English"],
  partnerPreferences: { ageMin: 23, ageMax: 30, religions: ["Jain"], cities: ["Surat", "Ahmedabad"], occupations: ["Any"] }
},

{
  name: "Vaibhav Shinde",
  email: "vaibhav@gmail.com",
  phoneNumber: "9876543269",
  password: "123456",
  photos: ["https://images.unsplash.com/photo-1522075469751-3a6694fb2f61"],
  gender: "Male",
  dateOfBirth: "1997-05-19",
  religion: "Hindu",
  motherTongue: "Marathi",
  maritalStatus: "Never Married",
  education: "B.Tech",
  occupation: "Salesforce Developer",
  city: "Aurangabad",
  state: "Maharashtra",
  bio: "CRM expert with a heart full of love.",
  hobbies: ["Gym", "Travel", "Cooking"],
  favoriteFoods: ["Naan Qalia", "Biryani"],
  favoriteColor: "Steel Blue",
  interests: ["Technology", "Fitness", "Travel"],
  personalityType: "Ambivert",
  height: 175,
  annualIncome: 1200000,
  drinking: "No",
  smoking: "No",
  languagesKnown: ["Marathi", "Hindi", "English"],
  partnerPreferences: { ageMin: 22, ageMax: 29, religions: ["Hindu"], cities: ["Aurangabad", "Pune"], occupations: ["Engineer", "Teacher"] }
},

// ══════════════════════════════════════
// FEMALE USERS (50)
// ══════════════════════════════════════

{
  name: "Priya Reddy",
  email: "priya@gmail.com",
  phoneNumber: "9876543211",
  password: "123456",
  photos: ["https://images.unsplash.com/photo-1494790108377-be9c29b29330"],
  gender: "Female",
  dateOfBirth: "1999-03-11",
  religion: "Hindu",
  motherTongue: "Telugu",
  maritalStatus: "Never Married",
  education: "MBA",
  occupation: "HR Manager",
  city: "Bangalore",
  state: "Karnataka",
  bio: "Family-oriented girl who loves traditions and travel.",
  hobbies: ["Cooking", "Music", "Reading"],
  favoriteFoods: ["Dosa", "Pasta"],
  favoriteColor: "Pink",
  interests: ["Travel", "Dance", "Fashion"],
  personalityType: "Extrovert",
  height: 162,
  annualIncome: 900000,
  drinking: "No",
  smoking: "No",
  languagesKnown: ["Telugu", "English"],
  partnerPreferences: { ageMin: 25, ageMax: 32, religions: ["Hindu"], cities: ["Hyderabad", "Bangalore"], occupations: ["Software Engineer", "Manager"] }
},

{
  name: "Sneha Patel",
  email: "sneha@gmail.com",
  phoneNumber: "9876543213",
  password: "123456",
  photos: ["https://images.unsplash.com/photo-1517841905240-472988babdf9"],
  gender: "Female",
  dateOfBirth: "2000-01-15",
  religion: "Hindu",
  motherTongue: "Gujarati",
  maritalStatus: "Never Married",
  education: "B.Com",
  occupation: "Accountant",
  city: "Ahmedabad",
  state: "Gujarat",
  bio: "Positive minded and cheerful person.",
  hobbies: ["Yoga", "Shopping", "Cooking"],
  favoriteFoods: ["Gujarati Thali", "Ice Cream"],
  favoriteColor: "Purple",
  interests: ["Travel", "Fitness"],
  personalityType: "Extrovert",
  height: 160,
  annualIncome: 700000,
  drinking: "No",
  smoking: "No",
  languagesKnown: ["Gujarati", "Hindi", "English"],
  partnerPreferences: { ageMin: 24, ageMax: 31, religions: ["Hindu"], cities: ["Ahmedabad", "Mumbai"], occupations: ["Business", "Engineer"] }
},
]   
// ========================
// INSERT USERS ONE BY ONE
// ========================

const insertUsers = async () => {

  try {

    for (const userData of users) {

      // Hash Password
      const salt = await bcrypt.genSalt(10);

      const hashedPassword = await bcrypt.hash(
        userData.password,
        salt
      );



      // Replace Password
      userData.password = hashedPassword;



      // Insert User
      const user = await User.create(userData);



      console.log(
        `✅ ${user.name} Inserted`
      );

    }



    console.log("================================");
    console.log("✅ All Users Inserted");
    console.log("================================");



    process.exit();

  } catch (error) {

    console.log(error);

    process.exit(1);

  }

};



insertUsers();